global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "ml_api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["<API_HOST>:5000"]
        labels:
          service: "ml_api"
