all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /home/pablo/.ssh/id_rsa
  children:
    api:
      hosts:
        api-server:
          ansible_host: 56.228.35.35
    monitoring:
      hosts:
        monitoring-server:
          ansible_host: 13.61.3.55
